# pyproject.toml  (preferred for new projects, PEP 621)

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "baselib"
version = "1.1.2"
description = "A base library for various utilities"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Daniel Balparda", email = "balparda@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
  "cryptography>=41.0.7",
  "Pillow>=10.2.0"
]

# test with:
# $ python3
# >>> import sys, tomli, pathlib
# >>> tomli.loads(pathlib.Path('pyproject.toml').read_text())
